using Google.Cloud.Firestore;
using System.ComponentModel.DataAnnotations;

namespace H4G_Project.Models
{
    [FirestoreData]

    public class VolunteerApplication
    {
        [FirestoreDocumentId]
        public string Id { get; set; } = string.Empty;

        /* Unique ID (optional, can be auto-generated by Firestore) */
        //[Display(Name = "User ID")]
        //public int MemberID { get; set; }

        [FirestoreProperty]
        [Display(Name = "Full Name")]
        [StringLength(50, ErrorMessage = "Name cannot exceed 50 characters")]
        [Required(ErrorMessage = "Please input caregiver name!")]
        public string Name { get; set; } = string.Empty;

        [FirestoreProperty]
        [Display(Name = "Occupation")]
        [StringLength(50, ErrorMessage = "Occupation cannot exceed 50 characters")]
        [Required(ErrorMessage = "Please input caregiver occupation!")]
        public string Occupation { get; set; } = string.Empty;

        [FirestoreProperty]
        [Display(Name = "Email")]
        [RegularExpression(@"^.+@.+\..+$", ErrorMessage = "Invalid Email")]
        [StringLength(50, ErrorMessage = "Email address cannot exceed 50 characters")]
        [Required(ErrorMessage = "Please input an email address!")]
        [EmailAddress]
        //[ValidateEmailExists]
        public string Email { get; set; } = string.Empty;

        [FirestoreProperty]
        [Display(Name = "Contact Number")]
        [Phone(ErrorMessage = "Invalid phone number")]
        public string ContactNumber { get; set; } = string.Empty;

        [FirestoreProperty]
        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        public string? DateOfBirth { get; set; }


        [FirestoreProperty]
        [Display(Name = "Additional Notes")]
        [StringLength(500, ErrorMessage = "Notes cannot exceed 500 characters")]
        public string Notes { get; set; } = string.Empty;

        [FirestoreProperty]
        public string ResumeUrl { get; set; } = string.Empty;

        [FirestoreProperty]
        [Display(Name = "Application Status")]
        public string Status { get; set; } = "Pending"; // Default status

    }
}
